---

- name: Create example configuration file for linbo repository
  template:
    src: "{{ item.src }}"
    dest: "{{ item.target }}"
    mode: "{{ item.mode | default(0640) }}"
    owner: root
    group: root
  with_items:
    - src: "linbo_gitignore.j2"
      target: "/var/linbo/.gitignore"
    # - src: "start.conf.j2"
      # target: "/var/linbo/examples/start.conf.ypid"
      # mode: 0644

- name: Create linbo system group configuration files
  template:
    src: "start.conf.j2"
    dest: "/var/linbo/start.conf.{{ item.name }}"
    mode: 0644
    owner: root
    group: root
  when: item is defined and item.name is string
  with_flattened:
    - linuxmuster_net_server_customize_system_groups

- name: Initialize git repository for linbo configuration
  command: git init
  args:
    creates: "/var/linbo/.git"
    chdir: "/var/linbo"
  register: linuxmuster_net_customize_linbo_git_init

- name: Change file permissions on .git directory to avoid read access via rsync
  file:
    path: "/var/linbo/.git"
    mode: "0750"
    owner: root
    group: root

- name: Initial commit git repository for linbo configuration
  shell: git add . && git commit --message "Initial commit."
  args:
    creates: "/var/linbo/.git/refs/heads/master"
    chdir: "/var/linbo"

- name: Copy custom linbo configuration files to the server
  synchronize:
    src: "./linbo"
    dest: "/var"
    recursive: yes
    links: yes
    set_remote_user: no
  tags: ci_ignore

- name: Install additional packages
  apt:
    name: "{{ item }}"
    state: 'latest'
  when: item is defined and item
  with_flattened:
    - linuxmuster_net_server_apt_packages
    - linuxmuster_net_server_apt_packages_group
    - linuxmuster_net_server_apt_packages_host
  tags: package_install
